apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
      - image: cercuit/udagram-frontend:v1
        name: frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "120Mi"
            cpu: "500m"
          limits:
            memory: "3024Mi"
            cpu: "1000m"
      restartPolicy: Always